"""
Author: nikhil.anand
Created at: 19/07/25
"""

from typing import List, Dict, Any
from transformers import pipeline, Pipeline
from app.constants.llm_constants import (
    GPT2_MODEL_MAX_NEW_TOKENS,
    GPT2_MODEL,
    GPT2_MODEL_DO_SAMPLE,
    GPT2_MODEL_TEMPERATURE,
)


class GPT2Model:
    """
    GPT-2 model wrapper for text generation and personalization.

    This class provides an interface to the GPT-2 language model for generating
    personalized text content. It handles model initialization, text generation,
    and post-processing of the generated content.

    Attributes:
        generator (Pipeline): Hugging Face transformers pipeline for text generation
    """

    def __init__(self) -> None:
        """
        Initialize the GPT-2 model with text generation pipeline.

        Sets up the Hugging Face transformers pipeline with the specified GPT-2 model
        and configures it for text generation tasks with float32 precision.
        """
        self.generator: Pipeline = pipeline("text-generation", model=GPT2_MODEL, torch_dtype="float32")

    @staticmethod
    def _extract_personalized_text(generated_text: str, prompt: str) -> str:
        """
        Extract only the personalized part from generated text.

        This method removes the original prompt from the generated text to return
        only the newly generated content, ensuring clean output without prompt repetition.

        Args:
            generated_text (str): The complete text generated by the model
            prompt (str): The original prompt used for generation

        Returns:
            str: The extracted personalized text without the prompt

        Example:
            >>> prompt = "Personalize this horoscope for John:"
            >>> generated = "Personalize this horoscope for John: Hello John, today..."
            >>> result = GPT2Model._extract_personalized_text(generated, prompt)
            >>> print(result)
            "Hello John, today..."
        """
        return generated_text[len(prompt) :].strip() if len(generated_text) > len(prompt) else generated_text

    def generate_personalized_test(self, prompt: str) -> str:
        """
        Generate personalized text based on the provided prompt.

        This method uses the GPT-2 model to generate personalized content based on
        the input prompt. It applies various generation parameters to control the
        quality and style of the output.

        Args:
            prompt (str): The input prompt for text generation

        Returns:
            str: The generated personalized text with the prompt removed

        Raises:
            Exception: If text generation fails or model is not properly initialized

        Example:
            >>> model = GPT2Model()
            >>> prompt = "Personalize this horoscope for John: Today is a good day."
            >>> result = model.generate_personalized_test(prompt)
            >>> print(result)
            "Hello John, today is indeed a wonderful day for you..."
        """
        result: List[Dict[str, Any]] = self.generator(
            prompt,
            max_new_tokens=GPT2_MODEL_MAX_NEW_TOKENS,
            # temperature=GPT2_MODEL_TEMPERATURE,  # Commented out due to potential conflicts
            do_sample=GPT2_MODEL_DO_SAMPLE,
            repetition_penalty=1.1,
            eos_token_id=self.generator.tokenizer.eos_token_id,
            pad_token_id=self.generator.tokenizer.eos_token_id,
        )
        generated_text: str = result[0]["generated_text"]
        personalized_text: str = self._extract_personalized_text(generated_text, prompt)
        return personalized_text
