"""
Author: nikhil.anand
Created at: 19/07/25
"""

from typing import List, Dict, Any
from transformers import pipeline, Pipeline

from app.constants.llm_constants import (
    TINY_LLAMA_MODEL_MAX_NEW_TOKENS,
    TINY_LLAMA_MODEL,
    TINY_LLAMA_MODEL_DO_SAMPLE,
    TINY_LLAMA_MODEL_TEMPERATURE,
)


class TinyLlamaModel:
    """
    TinyLlama model wrapper for text generation and personalization.

    This class provides an interface to the TinyLlama language model for generating
    personalized text content. TinyLlama is a smaller, more efficient model that
    can still produce quality text generation for personalization tasks.

    Attributes:
        generator (Pipeline): Hugging Face transformers pipeline for text generation
    """

    def __init__(self) -> None:
        """
        Initialize the TinyLlama model with text generation pipeline.

        Sets up the Hugging Face transformers pipeline with the specified TinyLlama model
        and configures it for text generation tasks with float32 precision.
        """
        self.generator: Pipeline = pipeline("text-generation", model=TINY_LLAMA_MODEL, torch_dtype="float32")

    @staticmethod
    def _extract_personalized_text(generated_text: str, prompt: str) -> str:
        """
        Extract only the personalized part from generated text.

        This method handles TinyLlama's specific output format, including the
        assistant token pattern, and removes the original prompt to return
        only the newly generated content.

        Args:
            generated_text (str): The complete text generated by the model
            prompt (str): The original prompt used for generation

        Returns:
            str: The extracted personalized text without the prompt

        Example:
            >>> prompt = "Personalize this horoscope:"
            >>> generated = "Personalize this horoscope: <|assistant|> Hello John, today..."
            >>> result = TinyLlamaModel._extract_personalized_text(generated, prompt)
            >>> print(result)
            "Hello John, today..."
        """
        if "<|assistant|>" in generated_text:
            response = generated_text.split("<|assistant|>")[-1].strip()
            return response
        return generated_text[len(prompt) :].strip() if len(generated_text) > len(prompt) else generated_text

    def generate_personalized_test(self, prompt: str) -> str:
        """
        Generate personalized text based on the provided prompt.

        This method uses the TinyLlama model to generate personalized content based on
        the input prompt. It applies various generation parameters including temperature
        and sampling to control the creativity and quality of the output.

        Args:
            prompt (str): The input prompt for text generation

        Returns:
            str: The generated personalized text with the prompt removed

        Raises:
            Exception: If text generation fails or model is not properly initialized

        Example:
            >>> model = TinyLlamaModel()
            >>> prompt = "Personalize this horoscope for Sarah: Today brings opportunities."
            >>> result = model.generate_personalized_test(prompt)
            >>> print(result)
            "Hello Sarah, today brings wonderful opportunities specifically for you..."
        """
        result: List[Dict[str, Any]] = self.generator(
            prompt,
            max_new_tokens=TINY_LLAMA_MODEL_MAX_NEW_TOKENS,
            temperature=TINY_LLAMA_MODEL_TEMPERATURE,
            do_sample=TINY_LLAMA_MODEL_DO_SAMPLE,
            repetition_penalty=1.1,
            eos_token_id=self.generator.tokenizer.eos_token_id,
            pad_token_id=self.generator.tokenizer.eos_token_id,
        )
        generated_text: str = result[0]["generated_text"]
        personalized_text: str = self._extract_personalized_text(generated_text, prompt)
        return personalized_text
